export default (
  '<div class="viewer-container" tabindex="-1" touch-action="none">'
    + '<div class="viewer-canvas"></div>'
    + '<div class="viewer-magnifier" aria-hidden="true">'
      + '<img class="viewer-magnifier-image" alt="">'
    + '</div>'
    + '<div class="viewer-navigation">'
      + '<div class="viewer-prev" data-viewer-action="prev" role="button" aria-label="Previous"></div>'
      + '<div class="viewer-next" data-viewer-action="next" role="button" aria-label="Next"></div>'
    + '</div>'
    + '<div class="viewer-footer">'
      + '<div class="viewer-title"></div>'
      + '<div class="viewer-toolbar"></div>'
      + '<div class="viewer-navbar">'
        + '<ul class="viewer-list" role="navigation"></ul>'
      + '</div>'
    + '</div>'
    + '<div class="viewer-tooltip" role="alert" aria-hidden="true"></div>'
    + '<div class="viewer-button" data-viewer-action="mix" role="button"></div>'
    + '<div class="viewer-player"></div>'
  + '</div>'
);
